POST http://localhost:3000/campaigns

{
    "name": "Mousepad",
    "description": "A new campaign",
    "emails": [
        "test@test.com"
    ]
}

###

GET  http://localhost:3000/campaigns


###

GET http://localhost:3000/campaigns/ef980c28-8317-4a2e-b6c5-d601644abbca